"""
Domain Interface — Cache Provider.

Infrastructure adapters (LRUCacheProvider, RedisCacheProvider, etc.)
implement this protocol.
"""

from __future__ import annotations

from typing import Protocol


class ICacheProvider(Protocol):
    """Contract for a key-value cache with TTL support."""

    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, *, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
    async def expire(self, key: str, ttl: int) -> None: ...
    async def incr(self, key: str) -> int: ...
    async def keys(self, pattern: str) -> list[str]: ...
    async def flush_namespace(self, namespace: str) -> None: ...
    async def health_check(self) -> bool: ...
    async def close(self) -> None: ...
